# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up Java 21
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew
      # Build the project
      - name: Build with Gradle
        run: ./gradlew build
#      # Run tests
#      - name: Run tests
#        run: ./gradlew test
      # Upload the JAR file as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: play-github-action-artifact.jar
          path: build/libs/*.jar
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Download the JAR file from the build job
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: play-github-action-artifact.jar
          path: play-github-action
      - name: Debug
        run: |
          ls -al play-github-action
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tranminhchien/project:latest
          platforms: linux/arm64
          context: play-github-action